# load libraries-------
library(gapminder)
library(tidyverse)
library(skimr)

# Explore the gapminder data -----
str(gapminder)
class(gapminder)
names(gapminder)
ncol(gapminder)
length(gapminder)
dim(gapminder)
nrow(gapminder)
summary(gapminder)
plot(lifeExp ~ year, gapminder)
plot(lifeExp ~ gdpPercap, gapminder)
summary(gapminder$lifeExp)
hist(gapminder$lifeExp)
summary(gapminder$year)
glimpse(gapminder)
skim(gapminder)
class(gapminder$continent)
levels(gapminder$continent)
table(gapminder$continent)
barplot(table(gapminder$continent))
